server:
  Name: user
  AppVersion: 1.0.0
  Port: :5002
  Mode: development
  JwtSecretKey: vdZwzfdGBIJ8133KR4fq7GRvLwEH1FI5
  ReadTimeout: 15s
  WriteTimeout: 15s
  MaxConnectionIdle: 5m
  Timeout: 15s
  MaxConnectionAge: 5m
  Time: 5m

logger:
  Encoding: console
  Level: debug

postgres:
  Host: localhost
  Port: 15432
  User: postgres
  Password: postgres
  DBName: account
  SSLMode: disable
  TZ: Asia/Jakarta

redis:
  Address: localhost:6379
  Password: admin
  DB: 0
  MinIdleConns: 200
  PoolSize: 12000
  PoolTimeout: 240

limiter:
  Limit: 50-S

kafka:
  brokers: [ "localhost:9092" ]
  groupID: user_consumer
  initTopics: false

refreshToken:
  MaxAge: 24h

accessToken:
  Expire: 3h

cache:
  Expire: 10m

gateway:
  Port: :6002

# container to container must use its own domain 
casbin:
  PostgresHost: postgres3
  PostgresPort: 5432
  PostgresUser: postgres
  PostgresPassword: postgres
  PostgresSslmode: disable
  PostgresTZ: Asia/Jakarta
  Url: localhost:50051

metrics:
  Url: localhost:7002
  ServiceName: grpc_user

jaeger:
  Host: localhost:6831
  ServiceName: grpc_user
  LogSpans: false
