// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: method.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MethodServiceClient is the client API for MethodService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MethodServiceClient interface {
	CreateMethod(ctx context.Context, in *CreateMethodRequest, opts ...grpc.CallOption) (*CreateMethodResponse, error)
	DeleteMethodById(ctx context.Context, in *DeleteMethodByIdRequest, opts ...grpc.CallOption) (*DeleteMethodByIdResponse, error)
	FindMethods(ctx context.Context, in *FindMethodsRequest, opts ...grpc.CallOption) (*FindMethodsResponse, error)
}

type methodServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMethodServiceClient(cc grpc.ClientConnInterface) MethodServiceClient {
	return &methodServiceClient{cc}
}

func (c *methodServiceClient) CreateMethod(ctx context.Context, in *CreateMethodRequest, opts ...grpc.CallOption) (*CreateMethodResponse, error) {
	out := new(CreateMethodResponse)
	err := c.cc.Invoke(ctx, "/pb.MethodService/CreateMethod", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *methodServiceClient) DeleteMethodById(ctx context.Context, in *DeleteMethodByIdRequest, opts ...grpc.CallOption) (*DeleteMethodByIdResponse, error) {
	out := new(DeleteMethodByIdResponse)
	err := c.cc.Invoke(ctx, "/pb.MethodService/DeleteMethodById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *methodServiceClient) FindMethods(ctx context.Context, in *FindMethodsRequest, opts ...grpc.CallOption) (*FindMethodsResponse, error) {
	out := new(FindMethodsResponse)
	err := c.cc.Invoke(ctx, "/pb.MethodService/FindMethods", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MethodServiceServer is the server API for MethodService service.
// All implementations must embed UnimplementedMethodServiceServer
// for forward compatibility
type MethodServiceServer interface {
	CreateMethod(context.Context, *CreateMethodRequest) (*CreateMethodResponse, error)
	DeleteMethodById(context.Context, *DeleteMethodByIdRequest) (*DeleteMethodByIdResponse, error)
	FindMethods(context.Context, *FindMethodsRequest) (*FindMethodsResponse, error)
	mustEmbedUnimplementedMethodServiceServer()
}

// UnimplementedMethodServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMethodServiceServer struct {
}

func (UnimplementedMethodServiceServer) CreateMethod(context.Context, *CreateMethodRequest) (*CreateMethodResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMethod not implemented")
}
func (UnimplementedMethodServiceServer) DeleteMethodById(context.Context, *DeleteMethodByIdRequest) (*DeleteMethodByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMethodById not implemented")
}
func (UnimplementedMethodServiceServer) FindMethods(context.Context, *FindMethodsRequest) (*FindMethodsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindMethods not implemented")
}
func (UnimplementedMethodServiceServer) mustEmbedUnimplementedMethodServiceServer() {}

// UnsafeMethodServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MethodServiceServer will
// result in compilation errors.
type UnsafeMethodServiceServer interface {
	mustEmbedUnimplementedMethodServiceServer()
}

func RegisterMethodServiceServer(s grpc.ServiceRegistrar, srv MethodServiceServer) {
	s.RegisterService(&MethodService_ServiceDesc, srv)
}

func _MethodService_CreateMethod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMethodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MethodServiceServer).CreateMethod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.MethodService/CreateMethod",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MethodServiceServer).CreateMethod(ctx, req.(*CreateMethodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MethodService_DeleteMethodById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMethodByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MethodServiceServer).DeleteMethodById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.MethodService/DeleteMethodById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MethodServiceServer).DeleteMethodById(ctx, req.(*DeleteMethodByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MethodService_FindMethods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindMethodsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MethodServiceServer).FindMethods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.MethodService/FindMethods",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MethodServiceServer).FindMethods(ctx, req.(*FindMethodsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MethodService_ServiceDesc is the grpc.ServiceDesc for MethodService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MethodService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.MethodService",
	HandlerType: (*MethodServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateMethod",
			Handler:    _MethodService_CreateMethod_Handler,
		},
		{
			MethodName: "DeleteMethodById",
			Handler:    _MethodService_DeleteMethodById_Handler,
		},
		{
			MethodName: "FindMethods",
			Handler:    _MethodService_FindMethods_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "method.proto",
}
