global:
  scrape_interval: 15s #* Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s #* Evaluate rules every 15 seconds. The default is every 1 minute.
  #* scrape_timeout is set to the global default (10s).

  #* Attach these labels to any time series or alerts when communicating with
  #* external systems (federation, remote storage, Alertmanager).
  # external_labels:
  #   monitor: "docker-host-alpha"

#* Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules"

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - "alertmanager:9093"

#* A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "nodeexporter"
    static_configs:
      - targets: ["nodeexporter:9100"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: "pushgateway"
    honor_labels: true
    static_configs:
      - targets: ["pushgateway:9091"]

  - job_name: "kafka"
    static_configs:
      - targets: ["jmx-kafka1:5556"]

  - job_name: "grpc-safety_gateway"
    static_configs:
      - targets: ["localhost:7000"]

  - job_name: "grpc-safety_auth"
    static_configs:
      - targets: ["localhost:7001"]

  - job_name: "grpc-safety_user"
    static_configs:
      - targets: ["localhost:7002"]

  - job_name: "grpc-safety_mail"
    static_configs:
      - targets: ["localhost:7003"]

  - job_name: "grpc-safety_core"
    static_configs:
      - targets: ["localhost:7004"]
#  - job_name: 'nginx'
#    scrape_interval: 10s
#    static_configs:
#      - targets: ['nginxexporter:9113']

#  - job_name: 'aspnetcore'
#    scrape_interval: 10s
#    static_configs:
#      - targets: ['eventlog-proxy:5000', 'eventlog:5000']
